# .github/workflows/publish.yml
name: HH Scraper & Publisher

on:
  schedule:
    # 12:00 Asia/Almaty
    - cron: '0 6 * * *'
    # 18:00 Asia/Almaty
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  hh_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache data folder (CSV + sent_links)
        uses: actions/cache@v3
        with:
          path: data
          key: hh-scraper-data

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper & publisher
        run: python run_all.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_USERNAME:    ${{ secrets.CHANNEL_USERNAME }}
          GEM_API_TOKEN:       ${{ secrets.GEM_API_TOKEN }}

      - name: Commit data changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --staged --quiet || git commit -m "ci: update scraped data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
